"""
Processes a directory containing PNGs generated by the EarthImageSimulator for a particular MGRS region, and merges them
into a single GeoTIFF saliency map using the latitude and longitude information generated by the simulator.
"""

import argparse
import os

import cv2
import numpy as np
from affine import Affine
from brahe.constants import R_EARTH

from image_simulation.earth_vis import GeoTIFFData
from utils.earth_utils import get_MGRS_grid
from VisionTrainingGround.DataPipeline.generate_training_data import LAT_LON_OUTPUT_FILE_SUFFIX

OUTPUT_FILE_NAME = "saliency_map.tif"


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    :return: The parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Create a GeoTIFF saliency map for a MGRS region from a directory of PNGs and .npy files."
    )
    parser.add_argument(
        "input_dir",
        type=str,
        help="The directory containing the PNGs and .npy files to use to generate the saliency map.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Whether to overwrite the output file if it exists.",
    )
    parser.add_argument(
        "--gsd",
        type=float,
        default=50.0,
        help="The ground sample distance to use for the saliency map.",
    )
    parser.add_argument(
        "--region",
        type=str,
        help="The MGRS region to generate the saliency map for."
        "If not provided, the region will be inferred from the input directory name.",
    )
    return parser.parse_args()


def generate_saliency_map(
    input_dir: str, output_file: str, gsd: float, region_id: str
) -> GeoTIFFData:
    """
    Generate a saliency map for a MGRS region from a directory of PNGs and .npy files.

    :param input_dir: The directory containing the PNGs and .npy files to use to generate the saliency map.
    :param output_file: The file to save the saliency map to.
    :param gsd: The ground sample distance to use for the saliency map.
    :param region_id: The MGRS region to generate the saliency map for.
    :return: The saliency map as a GeoTIFFData object.
    """
    file_names = os.listdir(input_dir)
    image_file_names = {name[:-4] for name in file_names if name.endswith(".png")}
    lat_lon_file_names = {
        name[: -len(LAT_LON_OUTPUT_FILE_SUFFIX)]
        for name in file_names
        if name.endswith(LAT_LON_OUTPUT_FILE_SUFFIX)
    }
    common_file_names = list(image_file_names & lat_lon_file_names)

    if len(image_file_names) != len(common_file_names):
        print(
            f"Warning: Some PNG files do not have corresponding lat/lon files: "
            f"{list(image_file_names - lat_lon_file_names)}"
        )
    if len(lat_lon_file_names) != len(common_file_names):
        print(
            f"Warning: Some lat/lon files do not have corresponding PNG files: "
            f"{list(lat_lon_file_names - image_file_names)}"
        )
    if len(common_file_names) == 0:
        raise ValueError("No matching PNG and lat/lon files found.")

    min_lon, min_lat, max_lon, max_lat = get_MGRS_grid()[region_id]
    height = (np.abs(max_lat - min_lat) / 360) * 2 * np.pi * R_EARTH / gsd
    top_width = (np.abs(max_lon - min_lon) / 360) * 2 * np.pi * R_EARTH * np.cos(max_lat) / gsd
    bottom_width = (np.abs(max_lon - min_lon) / 360) * 2 * np.pi * R_EARTH * np.cos(min_lat) / gsd
    height = int(np.ceil(height))
    width = int(np.ceil(np.maximum(top_width, bottom_width)))

    region_saliency_map = GeoTIFFData(
        image_path=output_file,
        image_data=np.zeros((height, width, 1), dtype=np.float32),
        transform=Affine.identity(),
    )
    region_saliency_map.remap_to_mgrs_region(region_id)
    region_saliency_map_counts = np.zeros((height, width), dtype=int)
    saliency_computer = cv2.saliency.StaticSaliencyFineGrained_create()

    for file_name in common_file_names:
        file_path = os.path.join(input_dir, file_name + ".png")
        image = cv2.imread(file_path)
        success, img_saliency_map = saliency_computer.computeSaliency(image)

        if not success:
            print(f"Warning: Failed to compute saliency map for: {file_path}.")
            continue

        assert (
            img_saliency_map.dtype == region_saliency_map.dtype
        ), f"Expected saliency map to have dtype {region_saliency_map.dtype}, but got {img_saliency_map.dtype}."

        lat_lon = np.load(os.path.join(input_dir, file_name + LAT_LON_OUTPUT_FILE_SUFFIX))
        assert (
            lat_lon.shape[:2] == image.shape[:2]
        ), f"Lat/lon shape {lat_lon.shape[:2]} does not match image shape {image.shape[:2]}."

        us, vs, valid_mask = region_saliency_map.get_pixel_coordinates(lat_lon)

        # cannot use += because it won't work with repeated indices
        np.add.at(
            region_saliency_map.image_data,
            (vs[valid_mask], us[valid_mask]),
            img_saliency_map[valid_mask],
        )
        np.add.at(region_saliency_map_counts, (vs[valid_mask], us[valid_mask]), 1)

    nonzero = region_saliency_map_counts > 0
    region_saliency_map.image_data[nonzero, :] /= region_saliency_map_counts[nonzero]
    return region_saliency_map


def main() -> None:
    """
    Script entry point.
    """
    args = parse_args()

    region = args.region if args.region is not None else os.path.basename(args.input_dir)
    output_file = os.path.join(args.input_dir, OUTPUT_FILE_NAME)
    if os.path.exists(output_file):
        if not args.overwrite:
            raise FileExistsError(f"Output file {output_file} already exists.")
        os.remove(output_file)

    saliency_map = generate_saliency_map(args.input_dir, output_file, args.gsd, region)
    saliency_map.save()


if __name__ == "__main__":
    main()
