"""
Processes a directory containing PNGs generated by the EarthImageSimulator for a particular MGRS region, and merges them
into a single GeoTIFF saliency map using the latitude and longitude information generated by the simulator.
The saliency map is then used to identify the top saliency bounding boxes, which are saved in CSV format.
The bounding boxes are then used to generate YOLO labels in the form of .txt files for each of the PNGs.
"""

import argparse
import os
from typing import List

import cv2
import numpy as np
from affine import Affine
from brahe.constants import R_EARTH
from scipy.ndimage import uniform_filter

from image_simulation.earth_vis import GeoTIFFData
from utils.earth_utils import get_MGRS_grid, lat_lon_to_ecef
from VisionTrainingGround.DataPipeline.generate_training_data import LAT_LON_OUTPUT_FILE_SUFFIX

SALIENCY_MAP_FILE_NAME = "saliency_map.tif"
BOUNDING_BOXES_FILE_NAME = "bounding_boxes.csv"


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    :return: The parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Create a GeoTIFF saliency map for a MGRS region from a directory of PNGs and .npy files."
    )
    parser.add_argument(
        "input_dir",
        type=str,
        help="The directory containing the PNGs and .npy files to use to generate the saliency map.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Whether to overwrite the output file if it exists.",
    )
    parser.add_argument(
        "--gsd",
        type=float,
        default=50.0,
        help="The ground sample distance to use for the saliency map.",
    )
    parser.add_argument(
        "--region",
        type=str,
        help="The MGRS region to generate the saliency map for."
        "If not provided, the region will be inferred from the input directory name.",
    )
    parser.add_argument(
        "--bounding_box_size",
        type=int,
        default=7200,
        help="The side length of the bounding boxes to find in the saliency map, in meters.",
    )
    parser.add_argument(
        "--num_boxes",
        type=int,
        default=50,
        help="The number of top saliency bounding boxes to identify.",
    )
    return parser.parse_args()


def get_common_file_name_prefixes(input_dir: str) -> List[str]:
    """
    Get the common file name prefixes for PNG and .npy lat/lon files in the input directory.
    A warning is printed if there are PNG files without corresponding lat/lon files, or vice versa.

    :param input_dir: The directory containing the PNGs and .npy files.
    :return: A list of common file name prefixes.
    """
    file_names = os.listdir(input_dir)
    image_file_prefixes = {name[:-4] for name in file_names if name.endswith(".png")}
    lat_lon_file_prefixes = {
        name[: -len(LAT_LON_OUTPUT_FILE_SUFFIX)]
        for name in file_names
        if name.endswith(LAT_LON_OUTPUT_FILE_SUFFIX)
    }
    common_file_prefixes = list(image_file_prefixes & lat_lon_file_prefixes)

    if len(image_file_prefixes) != len(common_file_prefixes):
        print(
            f"Warning: Some PNG files do not have corresponding lat/lon files: "
            f"{list(image_file_prefixes - lat_lon_file_prefixes)}"
        )
    if len(lat_lon_file_prefixes) != len(common_file_prefixes):
        print(
            f"Warning: Some lat/lon files do not have corresponding PNG files: "
            f"{list(lat_lon_file_prefixes - image_file_prefixes)}"
        )
    return common_file_prefixes


def generate_saliency_map(
    input_dir: str, output_file: str, gsd: float, region_id: str
) -> GeoTIFFData:
    """
    Generate a saliency map for a MGRS region from a directory of PNGs and .npy files.

    :param input_dir: The directory containing the PNGs and .npy files to use to generate the saliency map.
    :param output_file: The file to save the saliency map to.
    :param gsd: The ground sample distance to use for the saliency map.
    :param region_id: The MGRS region to generate the saliency map for.
    :return: The saliency map as a GeoTIFFData object.
    """
    file_prefixes = get_common_file_name_prefixes(input_dir)
    if len(file_prefixes) == 0:
        raise ValueError("No matching PNG and lat/lon files found.")

    min_lon, min_lat, max_lon, max_lat = get_MGRS_grid()[region_id]
    height = (np.abs(max_lat - min_lat) / 360) * 2 * np.pi * R_EARTH / gsd
    top_width = (np.abs(max_lon - min_lon) / 360) * 2 * np.pi * R_EARTH * np.cos(max_lat) / gsd
    bottom_width = (np.abs(max_lon - min_lon) / 360) * 2 * np.pi * R_EARTH * np.cos(min_lat) / gsd
    height = int(np.ceil(height))
    width = int(np.ceil(np.maximum(top_width, bottom_width)))

    region_saliency_map = GeoTIFFData(
        image_path=output_file,
        image_data=np.zeros((height, width, 1), dtype=np.float32),
        transform=Affine.identity(),
    )
    region_saliency_map.remap_to_mgrs_region(region_id)
    region_saliency_map_counts = np.zeros((height, width), dtype=int)
    saliency_computer = cv2.saliency.StaticSaliencyFineGrained_create()

    for file_prefix in file_prefixes:
        file_path = os.path.join(input_dir, file_prefix + ".png")
        image = cv2.imread(file_path)
        success, img_saliency_map = saliency_computer.computeSaliency(image)

        if not success:
            print(f"Warning: Failed to compute saliency map for: {file_path}.")
            continue

        assert (
            img_saliency_map.dtype == region_saliency_map.dtype
        ), f"Expected saliency map to have dtype {region_saliency_map.dtype}, but got {img_saliency_map.dtype}."

        lat_lon = np.load(os.path.join(input_dir, file_prefix + LAT_LON_OUTPUT_FILE_SUFFIX))
        assert (
            lat_lon.shape[:2] == image.shape[:2]
        ), f"Lat/lon shape {lat_lon.shape[:2]} does not match image shape {image.shape[:2]}."

        us, vs, valid_mask = region_saliency_map.get_pixel_coordinates(lat_lon)

        # cannot use += because it won't work with repeated indices
        np.add.at(
            region_saliency_map.image_data,
            (vs[valid_mask], us[valid_mask]),
            img_saliency_map[valid_mask],
        )
        np.add.at(region_saliency_map_counts, (vs[valid_mask], us[valid_mask]), 1)

    nonzero = region_saliency_map_counts > 0
    region_saliency_map.image_data[nonzero, :] /= region_saliency_map_counts[nonzero]
    return region_saliency_map


def find_best_bounding_boxes(
    saliency_map: GeoTIFFData, window_size: int, num_boxes: int
) -> np.ndarray:
    """
    Find the top saliency bounding boxes of the specified size within a saliency map.

    The returned bounding boxes are ordered from highest to lowest saliency, which also corresponds to the class IDs.

    :param saliency_map: The saliency map to generate bounding boxes for.
    :param window_size: The size of the bounding boxes to find in the saliency map. Must be odd.
    :param num_boxes: The number of top saliency boxes to identify.
    :return: A numpy array of shape (num_boxes, 6) containing (centroid_lon, centroid_lat, top_left_lon, top_left_lat,
             bottom_right_lon, bottom_right_lat) for each of the top saliency bounding boxes.
    """
    if window_size % 2 == 0:
        raise ValueError("Window size must be odd.")
    half_window_size = window_size // 2

    bounding_box_mean_saliencies = uniform_filter(
        saliency_map.image_data[..., 0], size=window_size, mode="constant", cval=0
    )

    # ensure resulting bounding boxes are strictly within the GeoTIFF bounds
    bounding_box_mean_saliencies[:half_window_size, :] = 0
    bounding_box_mean_saliencies[-half_window_size:, :] = 0
    bounding_box_mean_saliencies[:, :half_window_size] = 0
    bounding_box_mean_saliencies[:, -half_window_size:] = 0

    # use argpartition to avoid sorting the entire array
    top_indices = np.argpartition(bounding_box_mean_saliencies, -num_boxes, axis=None)[-num_boxes:]
    centroid_vs, centroid_us = np.unravel_index(top_indices, bounding_box_mean_saliencies.shape)
    # still need to sort the best bounding boxes so that the class IDs are in descending order of saliency
    sort_order = np.argsort(bounding_box_mean_saliencies[centroid_vs, centroid_us])[::-1]
    centroid_vs = centroid_vs[sort_order]
    centroid_us = centroid_us[sort_order]

    top_left_us = centroid_us - half_window_size
    top_left_vs = centroid_vs - half_window_size
    bottom_right_us = centroid_us + half_window_size
    bottom_right_vs = centroid_vs + half_window_size

    inverse_transform = ~saliency_map.transform
    centroid_lon, centroid_lat = inverse_transform * (centroid_us, centroid_vs)
    top_left_lon, top_left_lat = inverse_transform * (top_left_us, top_left_vs)
    bottom_right_lon, bottom_right_lat = inverse_transform * (bottom_right_us, bottom_right_vs)

    csv_data = np.column_stack(
        (centroid_lon, centroid_lat, top_left_lon, top_left_lat, bottom_right_lon, bottom_right_lat)
    )
    return csv_data


def generate_yolo_labels(input_dir: str) -> None:
    """
    Generate YOLO labels in the form of .txt files for each image in the input directory.

    Each .txt file contains one line for each bounding box that is entirely contained within the image.
    The line is formatted as follows, with all coordinates normalized to the range [0, 1]:
    <class_id> <u_center> <v_center> <box_width> <box_height>

    :param input_dir: The directory containing the PNGs, .npy files containing latitudes and longitudes, and the .csv
                      file containing the bounding box coordinates to use to generate the YOLO label files.
    """
    file_prefixes = get_common_file_name_prefixes(input_dir)
    if len(file_prefixes) == 0:
        raise ValueError("No matching PNG and lat/lon files found.")

    csv_data = np.loadtxt(
        os.path.join(input_dir, BOUNDING_BOXES_FILE_NAME), delimiter=",", skiprows=1
    )
    num_boxes = csv_data.shape[0]

    top_left_lat_lon = np.column_stack((csv_data[:, 3], csv_data[:, 2]))
    bottom_right_lat_lon = np.column_stack((csv_data[:, 5], csv_data[:, 4]))
    top_right_lat_lon = np.column_stack((top_left_lat_lon[:, 0], bottom_right_lat_lon[:, 1]))
    bottom_left_lat_lon = np.column_stack((bottom_right_lat_lon[:, 0], top_left_lat_lon[:, 1]))

    stacked_corners_lat_lon = np.stack(
        (top_left_lat_lon, top_right_lat_lon, bottom_left_lat_lon, bottom_right_lat_lon), axis=0
    )
    stacked_corners_ecef = lat_lon_to_ecef(stacked_corners_lat_lon)

    for file_prefix in file_prefixes:
        image_path = os.path.join(input_dir, file_prefix + ".png")
        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        height, width = image.shape[:2]

        lat_lon = np.load(os.path.join(input_dir, file_prefix + LAT_LON_OUTPUT_FILE_SUFFIX))
        assert (
            lat_lon.shape[:2] == image.shape[:2]
        ), f"Lat/lon shape {lat_lon.shape} does not match image shape {image.shape} for {file_prefix}."
        assert (
            lat_lon.shape[2] == 2
        ), f"Expected lat/lon shape to have 2 channels, but got {lat_lon.shape[2]}."
        pixel_coordinates_ecef = lat_lon_to_ecef(lat_lon).reshape(-1, 3)

        x_distances = np.subtract.outer(stacked_corners_ecef[:, 0], pixel_coordinates_ecef[:, 0])
        y_distances = np.subtract.outer(stacked_corners_ecef[:, 1], pixel_coordinates_ecef[:, 1])
        z_distances = np.subtract.outer(stacked_corners_ecef[:, 2], pixel_coordinates_ecef[:, 2])
        # column_stack should be faster than row_stack because it means that the norm operates across contiguous memory
        distances = np.linalg.norm(np.column_stack((x_distances, y_distances, z_distances)), axis=1)
        assert distances.shape == (4 * num_boxes, height * width)

        closest_pixel_indices = np.argmin(distances, axis=1)
        closest_vs, closest_us = np.unravel_index(closest_pixel_indices, (height, width))

        # reject any bounding boxes that have a corner whose closest pixel is on the boundary of the image
        valid_box_corners = (
            (closest_us > 0)
            & (closest_us < width - 1)
            & (closest_vs > 0)
            & (closest_vs < height - 1)
        )
        valid_bounding_boxes = np.all(valid_box_corners.reshape(num_boxes, 4), axis=1)
        class_ids = np.arange(num_boxes)[valid_bounding_boxes]

        # widen bounding boxes to the smallest axis-aligned bounding box that contains all 4 corners
        valid_box_corners = np.tile(valid_bounding_boxes, 4)
        closest_us = closest_us[valid_box_corners].reshape(-1, 4)
        closest_vs = closest_vs[valid_box_corners].reshape(-1, 4)
        min_us = np.min(closest_us, axis=1)
        max_us = np.max(closest_us, axis=1)
        min_vs = np.min(closest_vs, axis=1)
        max_vs = np.max(closest_vs, axis=1)

        # convert to YOLO format
        u_center = (min_us + max_us) / (2 * width)
        v_center = (min_vs + max_vs) / (2 * height)
        box_width = (max_us - min_us) / width
        box_height = (max_vs - min_vs) / height

        with open(os.path.join(input_dir, f"{file_prefix}.txt"), "w") as file:
            for class_id, u, v, w, h in zip(class_ids, u_center, v_center, box_width, box_height):
                file.write(f"{class_id} {u} {v} {w} {h}\n")


def main() -> None:
    """
    Script entry point.
    """
    args = parse_args()

    region = args.region if args.region is not None else os.path.basename(args.input_dir)
    output_file = os.path.join(args.input_dir, SALIENCY_MAP_FILE_NAME)
    if os.path.exists(output_file):
        if not args.overwrite:
            raise FileExistsError(f"Output file {output_file} already exists.")
        os.remove(output_file)

    saliency_map = generate_saliency_map(args.input_dir, output_file, args.gsd, region)
    saliency_map.save()

    window_size = args.bounding_box_size / args.gsd
    # round to the nearest odd integer
    window_size = 2 * int(np.rint((window_size - 1) / 2)) + 1
    csv_data = find_best_bounding_boxes(saliency_map, window_size, args.num_boxes)
    np.savetxt(
        os.path.join(args.input_dir, BOUNDING_BOXES_FILE_NAME),
        csv_data,
        delimiter=",",
        header="Centroid Longitude,Centroid Latitude,Top-Left Longitude,"
        "Top-Left Latitude,Bottom-Right Longitude,Bottom-Right Latitude",
    )

    generate_yolo_labels(args.input_dir)


if __name__ == "__main__":
    main()
