"""
Processes a directory containing PNGs generated by the EarthImageSimulator for a particular MGRS region and the results
of running salient region analysis to prepare the data for training a YOLO model.
"""

import argparse
import os
from typing import List

import cv2
import numpy as np

from utils.earth_utils import lat_lon_to_ecef
from VisionTrainingGround.DataPipeline.generate_training_data import LAT_LON_OUTPUT_FILE_SUFFIX
from VisionTrainingGround.LD.generate_saliency_map import (
    BOUNDING_BOXES_FILE_NAME,
    get_common_file_name_prefixes,
)


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    :return: The parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Process a directory containing PNGs generated by the EarthImageSimulator and the results of "
        "running salient region analysis to prepare the data for training a YOLO model."
    )
    parser.add_argument(
        "input_dir",
        type=str,
        help="The directory containing the PNGs, the saliency map .tiff file, and bounding boxes .csv file to use.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Whether to overwrite the output files if they exist.",
    )
    return parser.parse_args()


def generate_yolo_labels(input_dir: str, file_prefixes: List[str]) -> None:
    """
    Generate YOLO labels in the form of .txt files for each image in the input directory.

    Each .txt file contains one line for each bounding box that is entirely contained within the image.
    The line is formatted as follows, with all coordinates normalized to the range [0, 1]:
    <class_id> <u_center> <v_center> <box_width> <box_height>

    :param input_dir: The directory containing the PNGs, .npy files containing latitudes and longitudes, and the .csv
                      file containing the bounding box coordinates to use to generate the YOLO label files.
    :param file_prefixes: The common prefixes of the PNG and lat/lon files to process.
    """
    csv_data = np.loadtxt(
        os.path.join(input_dir, BOUNDING_BOXES_FILE_NAME), delimiter=",", skiprows=1
    )
    num_boxes = csv_data.shape[0]

    top_left_lat_lon = np.column_stack((csv_data[:, 3], csv_data[:, 2]))
    bottom_right_lat_lon = np.column_stack((csv_data[:, 5], csv_data[:, 4]))
    top_right_lat_lon = np.column_stack((top_left_lat_lon[:, 0], bottom_right_lat_lon[:, 1]))
    bottom_left_lat_lon = np.column_stack((bottom_right_lat_lon[:, 0], top_left_lat_lon[:, 1]))

    stacked_corners_lat_lon = np.stack(
        (top_left_lat_lon, top_right_lat_lon, bottom_left_lat_lon, bottom_right_lat_lon), axis=0
    )
    stacked_corners_ecef = lat_lon_to_ecef(stacked_corners_lat_lon)

    for file_prefix in file_prefixes:
        image_path = os.path.join(input_dir, file_prefix + ".png")
        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        height, width = image.shape[:2]

        lat_lon = np.load(os.path.join(input_dir, file_prefix + LAT_LON_OUTPUT_FILE_SUFFIX))
        assert (
            lat_lon.shape[:2] == image.shape[:2]
        ), f"Lat/lon shape {lat_lon.shape} does not match image shape {image.shape} for {file_prefix}."
        assert (
            lat_lon.shape[2] == 2
        ), f"Expected lat/lon shape to have 2 channels, but got {lat_lon.shape[2]}."
        pixel_coordinates_ecef = lat_lon_to_ecef(lat_lon).reshape(-1, 3)

        x_distances = np.subtract.outer(stacked_corners_ecef[:, 0], pixel_coordinates_ecef[:, 0])
        y_distances = np.subtract.outer(stacked_corners_ecef[:, 1], pixel_coordinates_ecef[:, 1])
        z_distances = np.subtract.outer(stacked_corners_ecef[:, 2], pixel_coordinates_ecef[:, 2])
        # surprisingly row_stack is actually faster than column_stack here, probably because of the overhead in
        # creating the stacked array (https://chatgpt.com/share/67ce49e5-e1c8-800c-b931-b3862d7d299f)
        distances = np.linalg.norm(np.row_stack((x_distances, y_distances, z_distances)), axis=0)
        assert distances.shape == (4 * num_boxes, height * width)

        closest_pixel_indices = np.argmin(distances, axis=1)
        closest_vs, closest_us = np.unravel_index(closest_pixel_indices, (height, width))

        # reject any bounding boxes that have a corner whose closest pixel is on the boundary of the image
        valid_box_corners = (
            (closest_us > 0)
            & (closest_us < width - 1)
            & (closest_vs > 0)
            & (closest_vs < height - 1)
        )
        valid_bounding_boxes = np.all(valid_box_corners.reshape(num_boxes, 4), axis=1)
        class_ids = np.arange(num_boxes)[valid_bounding_boxes]

        # widen bounding boxes to the smallest axis-aligned bounding box that contains all 4 corners
        valid_box_corners = np.tile(valid_bounding_boxes, 4)
        closest_us = closest_us[valid_box_corners].reshape(-1, 4)
        closest_vs = closest_vs[valid_box_corners].reshape(-1, 4)
        min_us = np.min(closest_us, axis=1)
        max_us = np.max(closest_us, axis=1)
        min_vs = np.min(closest_vs, axis=1)
        max_vs = np.max(closest_vs, axis=1)

        # convert to YOLO format
        u_center = (min_us + max_us) / (2 * width)
        v_center = (min_vs + max_vs) / (2 * height)
        box_width = (max_us - min_us) / width
        box_height = (max_vs - min_vs) / height

        with open(os.path.join(input_dir, f"{file_prefix}.txt"), "w") as file:
            for class_id, u, v, w, h in zip(class_ids, u_center, v_center, box_width, box_height):
                file.write(f"{class_id} {u} {v} {w} {h}\n")


def main():
    args = parse_args()

    file_prefixes = get_common_file_name_prefixes(args.input_dir)
    if len(file_prefixes) == 0:
        raise ValueError("No matching PNG and lat/lon files found.")

    for file_prefix in file_prefixes:
        file_path = os.path.join(args.input_dir, f"{file_prefix}.txt")
        if os.path.exists(file_path):
            if not args.overwrite:
                raise FileExistsError(
                    f"Output file {file_prefix}.txt already exists. Use --overwrite to overwrite."
                )
            os.remove(file_path)

    generate_yolo_labels(args.input_dir, file_prefixes)


if __name__ == "__main__":
    main()
