# Path to the folder containing directories named with MGRS region IDs containing geotiff files used for image simulation
geotiff_folder: /path/to/geotiff/folder
# The name of the Earth Engine project that will be used by image_simulator/eedl.py to fetch the geotiff files
earth_engine_project_name: your_earth_engine_project_name
# The directory where the Blue Marble Next Generation dataset is stored
blue_marble_directory: /path/to/blue_marble/directory
# The directory where the training data is stored as it is being generated, processed, labelled, and trained on
# If you are working with multiple datasets, just pick one to use for the script you are running
training_directory: /path/to/training/directory
# The directory where the trained models will be loaded from
# If you train your own models, the models_directory can be the same as the training_directory
models_directory: /path/to/models/directory
# The directory where the output files from the result of running the files in the scripts directory will be saved
output_directory: /path/to/output/directory
