flags: 
  train_flag : True
  save_plot_flag : True
paths: 
  data_dir : "/home/argus/Arvind/eedl/landsat_images_train"
  model_save_path : "/home/argus/Arvind/GNC-Payload/VisionTrainingGround/RCnet/model/model1.pth"
  model_load_path : "/home/argus-vision/vision/VisionTrainingGround/RCnet/model/model.pth"
  save_plot_path : "/home/argus/Arvind/GNC-Payload/VisionTrainingGround/RCnet/results/loss_vs_epoch.png"
  
hyperparameters:
  learning_rate : 0.0001
  epochs : 50
