flags: 
  train_flag : True
  save_plot_flag : True
paths: 
  data_dir : "/home/pvijayba/baja_california_training/filled_baja_california"
  model_save_path : "/home/pvijayba/baja_california_training/models/region_classifier_model.pth"
  model_load_path : "/home/pvijayba/baja_california_training/models/region_classifier_model.pth"
  save_plot_path : "/home/pvijayba/baja_california_training/outputs/loss_plot.png"
  
hyperparameters:
  learning_rate : 0.0001
  epochs : 50
