"""
This script is designed to run the EarthImageSimulator class and generate an image for a given spacecraft position, attitude and camera model.
It requires the following arguments:
    --name: Name of the experiment
    --meas_rate: Rate at which measurements should be taken

The script requires as input the spacecraft trajectory and attitude, which are generated by the run_dynamics script and should be stored as: 
- /output_dir
    - /experiment_name
        - ground_truth.npz
            - attitude
            - trajectory
            - daytime
        - args.json

The script will generate (append in the args.json case) the following contents in the output directory:
- /output_dir
    - /experiment_name
        -/images
            -/<timestep>
                - img_<timestep>_<camera_name>.png
                - lat_lon_<timestep>_<camera_name>.npy

        - args.json
"""
import argparse
import gc
import json
import os
from functools import partial
from multiprocessing import Pool, cpu_count

import brahe
import cv2
import numpy as np
from brahe.epoch import Epoch
from tqdm import tqdm

from image_simulation.earth_vis import EarthImageSimulator, GeoTIFFCache
from sensors.camera_model import CameraModelManager
from utils.brahe_utils import increment_epoch
from utils.config_utils import USER_CONFIG_PATH, load_config
from utils.function_utils import unpack_and_call


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the image simulator at periodic intervals along the saved trajectory.",
    )
    parser.add_argument("--name", type=str, default="test", help="Name of the experiment")
    parser.add_argument("--meas_rate", type=int, default=120, help="Measurement rate")
    parser.add_argument(
        "--skip_night",
        action="store_true",
        help="Whether to skip generating images that are over the dark half of the Earth.",
    )
    parser.add_argument(
        "--num_processes",
        type=int,
        default=int(0.8 * cpu_count()),
        help="Number of processes to use for image generation",
    )
    return parser.parse_args()


def generate_image(index: int, camera_name: str, output_dir: str, args_json_path: str):
    # Load only inside worker
    trajectory = np.load(os.path.join(output_dir, "trajectory_gt.npy"))
    attitude = np.load(os.path.join(output_dir, "attitude_gt.npy"))
    with open(args_json_path, "r") as jsonfile:
        arg_data = json.load(jsonfile)

    starting_epoch = Epoch(*brahe.time.mjd_to_caldate(arg_data["start_date"]))
    dt = 1 / arg_data["frequency"]

    curr_epoch = increment_epoch(starting_epoch, index * dt)
    ecef_R_eci = brahe.frames.rECItoECEF(curr_epoch)
    position_ecef = ecef_R_eci @ trajectory[index, 0:3]
    attitude_matrix = attitude[index]

    earth_image_sim = EarthImageSimulator(
        geotiff_cache=GeoTIFFCache(max_cache_size=0),
        inpaint_blue_marble=True,
        blue_marble_month=None,
    )
    camera_model_manager = CameraModelManager()
    camera_model = camera_model_manager[camera_name]

    frame, lat_lon = earth_image_sim.simulate_image_for_training(
        position_ecef, attitude_matrix, camera_model
    )

    suffix = f"{index}_{camera_name}"
    image_dir = os.path.join(output_dir, "images")
    os.makedirs(image_dir, exist_ok=True)
    cv2.imwrite(
        os.path.join(image_dir, f"img_{suffix}.png"), cv2.cvtColor(frame.image, cv2.COLOR_RGB2BGR)
    )
    np.savez_compressed(os.path.join(image_dir, f"lat_lon_{suffix}.npz"), lat_lon=lat_lon)
    del trajectory, attitude, camera_model, earth_image_sim, frame, lat_lon
    gc.collect()


def request_generator(trajectory_len, meas_rate):
    for i in range(trajectory_len):
        if i % meas_rate == 0:
            for camera_name in CameraModelManager.CAMERA_NAMES:
                yield (i, camera_name)


def image_vis(args):
    output_dir = os.path.join(load_config(USER_CONFIG_PATH)["output_dir"], args.name)
    args_json_path = os.path.join(output_dir, "args.json")

    if not os.path.exists(f"{output_dir}/ground_truth.npz"):
        raise FileNotFoundError(
            "Missing input files, please run the trajectory generation script first."
        )

    with open(args_json_path, "r") as jsonfile:
        arg_data = json.load(jsonfile)

    arg_data["meas_rate"] = args.meas_rate
    arg_data["num_processes"] = args.num_processes

    with open(args_json_path, "w") as jsonfile:
        json.dump(arg_data, jsonfile, indent=4)

    trajectory_len = np.load(f"{output_dir}/ground_truth.npz")["trajectory"].shape[0]

    func = partial(generate_image, output_dir=output_dir, args_json_path=args_json_path)
    requests = request_generator(trajectory_len, args.meas_rate)

    with Pool(args.num_processes) as pool:
        list(
            tqdm(
                pool.imap_unordered(partial(unpack_and_call, func), requests, chunksize=1),
                total=sum(1 for _ in request_generator(trajectory_len, args.meas_rate)),
                desc="Generating images",
            )
        )


if __name__ == "__main__":
    image_vis(parse_args())
