"""
This script is designed to run the EarthImageSimulator class and generate an image for a given spacecraft position, attitude and camera model.
It requires the following arguments:
    --name: Name of the experiment
    --meas_rate: Rate at which measurements should be taken

The script requires as input the spacecraft trajectory and attitude, which are generated by the run_dynamics script and should be stored as: 
- /output_dir
    - /experiment_name
        - trajectory_gt.npy
        - attitude_gt.npy
        - daytime.npy

The script will generate the following contents in the output directory:
- /output_dir
    - /experiment_name
        -/images
            - img_<timestep>_<camera_name>.png
            - lat_lon_<timestep>_<camera_name>.npy
"""

import os
from argparse import ArgumentParser
from functools import partial
from multiprocessing import cpu_count

import numpy as np
import cv2

from image_simulation.earth_vis import EarthImageSimulator
from sensors.camera_model import CameraModelManager
from utils.memory_aware_process_pool import MemoryAwareProcessPool


def generate_image(position: np.ndarray, attitude: np.ndarray, camera_name: str, index: int, output_dir: str) -> None:
    """
    Generate an image and lat/lon .npy file for a given position, attitude, and camera model.

    :param position: The position of the spacecraft in ECEF coordinates.
    :param attitude: A numpy array of shape (3, 3) representing the rotation matrix from body to ECEF frame.
    :param camera_name: The name of the camera model to use.
    :param index: The index in the trajectory that the image corresponds to.
    :param output_dir: The directory to save the generated image.
    """
    earth_image_sim = EarthImageSimulator(
        geotiff_cache=None, inpaint_blue_marble=True, blue_marble_month=None
    )
    camera_model_manager = CameraModelManager()
    camera_model = camera_model_manager[camera_name]

    frame, lat_lon = earth_image_sim.simulate_image_for_training(position, attitude, camera_model)

    suffix = f"{index}_{camera_name}"
    cv2.imwrite(
        os.path.join(output_dir, f"img_{suffix}.png"),
        cv2.cvtColor(frame, cv2.COLOR_RGB2BGR),
    )
    np.save(
        os.path.join(output_dir, f"lat_lon_{suffix}.npy"),
        lat_lon,
    )


def image_vis(args) -> None:
    """
    Visualize earth for a set of positions and attitudes using all available cameras.
    :param: args
    """
    if (
        not os.path.exists(f"output_dir/{args.name}/trajectory_gt.npy")
        or not os.path.exists(f"output_dir/{args.name}/attitude_gt.npy")
        or not os.path.exists(f"output_dir/{args.name}/daytime_gt.npy")
    ):
        raise FileNotFoundError(
            f"One of the required files in {args.name} does not exist. Please run the trajectory generation script first."
        )
    trajectory_gt = np.load(f"output_dir/{args.name}/trajectory_gt.npy")
    attitude_gt = np.load(f"output_dir/{args.name}/attitude_gt.npy")
    daytime_gt = np.load(f"output_dir/{args.name}/daytime_gt.npy")

    if not os.path.exists(f"output_dir/{args.name}/images"):
        os.makedirs(f"output_dir/{args.name}/images")

    requests = []
    for i, state in enumerate(trajectory_gt):
        # Only run the earth image visualizer if it's a measurement step and daytime
        if i % args.meas_rate == 0 and daytime_gt[i]:
            for camera_name in CameraModelManager.CAMERA_NAMES:
                # TODO: bug fix: convert from ECI to ECEF
                requests.append((state[0:3], attitude_gt[i], camera_name, i))

    with MemoryAwareProcessPool(num_workers=args.num_processes) as pool:
        pool.map(
            partial(generate_image, output_dir=f"output_dir/{args.name}/images"),
            requests,
        )


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        "--name",
        type=str,
        default="test",
        help="Name of the experiment",
    )
    parser.add_argument(
        "--meas_rate",
        type=str,
        default=120,
        help="Rate at which measurements should be taken",
    )
    parser.add_argument(
        "--num_processes",
        type=int,
        default=int(0.5 * cpu_count()),
        help="Number of processes to use for image generation",
    )

    args = parser.parse_args()
    image_vis(args)
