"""
This script is designed to run the EarthImageSimulator class and generate an image for a given spacecraft position, attitude and camera model.
It requires the following arguments:
    --name: Name of the experiment
    --meas_rate: Rate at which measurements should be taken

The script requires as input the spacecraft trajectory and attitude, which are generated by the run_dynamics script and should be stored as: 
- /output_dir
    - /experiment_name
        - trajectory_gt.npy
        - attitude_gt.npy
        - daytime.npy

The script will generate the following contents in the output directory:
- /output_dir
    - /experiment_name
        - image_0.png
        - image_1.png
        - ...
        - image_n.png
"""

# TODO: Consider what a good naming scheme for these images is.

from argparse import ArgumentParser
import os

import numpy as np

from image_simulation.earth_vis import EarthImageSimulator
from sensors.camera_model import CameraModelManager
from utils.config_utils import load_config


def image_vis(args) -> None:
    """
    Visualize earth for a set of positions and attitudes using all available cameras.
    :param: args
    """
    # TODO: Check what the correct/necessary approaches regarding geotiff_caches and blue marble set are
    earth_image_sim = EarthImageSimulator(
        geotiff_cache=None, inpaint_blue_marble=False, blue_marble_month=None
    )
    camera_model_manager = CameraModelManager()

    # TODO
    if (
        not os.path.exists(f"output_dir/{args.name}/trajectory_gt.npy")
        or not os.path.exists(f"output_dir/{args.name}/attitude_gt.npy")
        or not os.path.exists(f"output_dir/{args.name}/daytime_gt.npy")
    ):
        raise FileNotFoundError(
            f"One of the required files in {args.name} does not exist. Please run the trajectory generation script first."
        )
    trajectory_gt = np.load(f"output_dir/{args.name}/trajectory_gt.npy")
    attitude_gt = np.load(f"output_dir/{args.name}/attitude_gt.npy")
    daytime_gt = np.load(f"output_dir/{args.name}/daytime_gt.npy")

    for i, state in enumerate(trajectory_gt):
        # Only run the earth image visualizer if it's a measurement step and it's daytime
        if i % args.meas_rate == 0 and daytime_gt[i]:
            for camera_name in CameraModelManager.CAMERA_NAMES:
                img = earth_image_sim.simulate_image(state[0:3], attitude_gt[i], camera_model_manager[camera_name])
                #TODO: Store the image


    # Load trajectory, attitude and day/night time from .npy (check that it exists)
    # Generate images for a set timestep range (every 120, should probably parameterize and add to filter as well).
    # Generate an image for every camera (use the camera model manager class for this)

    # Store images with timestamp as name?


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        "--name",
        type=str,
        default="test",
        help="Name of the experiment",
    )
    parser.add_argument(
        "--meas_rate",
        type=str,
        default=120,
        help="Rate at which measurements should be taken",
    )

    args = parser.parse_args()
    image_vis(args)
